Harvest.setFood("strawberry","Strawberry",1);
Harvest.setFood("raspberry","Raspberry",1);
Harvest.setFood("cranberry","Cranberry",1);
Harvest.setFood("blueberry","Blueberry",1);
Harvest.setFood("blackberry","Blackberry",1);
Harvest.setFood("candleberry","Candle berry",1);
Harvest.setFood("grape","Grape",1);
Harvest.setFood("cucumber","Cucumber",1);
Harvest.setFood("onion","Onion",1);
Harvest.setFood("cabbage","Cabbage",1);
Harvest.setFood("tomato","Tomato",1);
Harvest.setFood("bellpepper","Bellpepper",1);
Harvest.setFood("garlic","Garlic",1);
Harvest.setFood("lettuce","Lettuce",1);
Harvest.setFood("coffee_beans","Coffee beans",1);
Harvest.setFood("peas","Peas",1);
Harvest.setFood("chili_pepper","Chilli pepper",1);
Harvest.setFood("spice_leaf","Spice leaf",1);
Harvest.setFood("corn","Corn",1);
Harvest.setFood("curryleaf","Curryleaf",1);
Harvest.setFood("cotton","Cotton",1);
Harvest.setFood("bean","Bean",1);
Harvest.setFood("rice","Rice",1);
Harvest.setFood("waterchestnut","Water Chestnut",1);
Harvest.setFood("rutabaga","Rutabaga",1);
Harvest.setFood("mustardseeds","Mustard Seeds",1);
Harvest.setFood("ginger","Ginger",1);
Harvest.setFood("spinach","Spinach",1);
Harvest.setFood("cactusfruit","Cactusfruit",1);
Harvest.setFood("cantaloupe","Cantaloupe",1);
Harvest.setFood("kiwi","Kiwi",1);
Harvest.setFood("pineapple","Pineapple",1);
Harvest.setFood("artichoke","Artichoke",1);
Harvest.setFood("asparagus","Asparagus",1);
Harvest.setFood("bambooshoot","Bambooshoot",1);
Harvest.setFood("broccoli","Broccoli",1);
Harvest.setFood("brusselsprout","Brusselsprout",1);
Harvest.setFood("cauliflower","Cauliflower",1);
Harvest.setFood("celery","Celery",1);
Harvest.setFood("radish","Radish",1);
Harvest.setFood("eggplant","Eggplant",1);
Harvest.setFood("leek","Leek",1);
Harvest.setFood("okra","Okra",1);
Harvest.setFood("parsnip","Parsnip",1);
Harvest.setFood("rhubarb","Rhubarb",1);
Harvest.setFood("scallion","Scallion",1);
Harvest.setFood("soybean","Soybean",1);
Harvest.setFood("sweetpotato","Sweet Potato",1);
Harvest.setFood("turnip","Turnip",1);
Harvest.setFood("peanut","Peanut",1);
Harvest.setFood("rye","Rye",1);
Harvest.setFood("zucchini","Zucchini",1);
Harvest.setFood("barley","Barley",1);
Harvest.setFood("oats","Oats",1);
Harvest.setFood("beet","Beet",1);
Harvest.setFood("wintersquash","Wintersquash",1);
IDRegistry.genItemID("tealeaf");
Item.createItem("tealeaf", "Tea leaf", {name: "tealeaf", meta: 0});