//single, double, triple, quadruple,quintuple, sextuple, septuple, octuple, nonuple, decuple.

//SINGLE:
Compress.Local.RU("Single Compressed Cobblestone","Сжатый булыжник");
Compress.Local.RU("Single Compressed Stone","Сжатый камень");
Compress.Local.RU("Single Compressed Sand","Сжатый песок");
Compress.Local.RU("Single Compressed Dirt","Сжатая земля");
Compress.Local.RU("Single Compressed Gravel","Сжатый гравий");
Compress.Local.RU("Single Compressed Mossy Cobblestone","Сжатый замшелый булыжник");
Compress.Local.RU("Single Compressed End Stone","Сжатый камень Края");
Compress.Local.RU("Single Compressed Charcoal","Сжатый древесно-угольный блок");
Compress.Local.RU("Single Compressed Netherrack","Сжатый камень Нижнего мира");
Compress.Local.RU("Single Compressed Soul Sand","Сжатый песок душ");
Compress.Local.RU("Block of Log Oak","Блок из древесины дуба");
Compress.Local.RU("Block of Log Spruce","Блок из древесины сосны");
Compress.Local.RU("Block of Log Birch","Блок из древесины берёзы");
Compress.Local.RU("Block of Log Jungle","Блок из тропической древесина");
Compress.Local.RU("Block of Log Acacia","Блок из древесины акации");
Compress.Local.RU("Block of Log Dark Oak","Блок из древесины темного дуба");
Compress.Local.RU("Single Compressed Feathers","Сжатые перья");
Compress.Local.RU("Block of Strings","Блок из нитей");
Compress.Local.RU("Single Compressed Porkchop","Сжатая свинина");
Compress.Local.RU("Single Compressed Chicken","Сжатая курица");
Compress.Local.RU("Single Compressed Beef","Сжатая говядина");
Compress.Local.RU("Single Compressed Fish","Сжатая рыба");
Compress.Local.RU("Single Compressed Bones","Сжатые кости");
Compress.Local.RU("Single Compressed Eggs","Сжатые яйца");
Compress.Local.RU("Single Compressed Leather","Сжатая кожа");
Compress.Local.RU("Block of Bread","Блок из хлеба");
Compress.Local.RU("Block of Cookies","Блок из печеньев");
Compress.Local.RU("Single Compressed Potatoes","Сжатый картофель");
Compress.Local.RU("Single Compressed Carrots","Сжатая морковь");
Compress.Local.RU("Single Compressed Nether Wart","Сжатый адский нарост");
Compress.Local.RU("Single Compressed Melon","Сжатый арбуз");
Compress.Local.RU("Single Compressed Apples","Сжатое яблоко");
Compress.Local.RU("Single Compressed Rotten Flesh","Сжатая гнилая плоть");
Compress.Local.RU("Single Compressed Blaze","Сжатый огненный стержень");
Compress.Local.RU("Single Compressed Spider Eyes","Сжатые паучьи глаза");
Compress.Local.RU("Single Compressed Ender Pearl","Сжатый жемчуг Края");
Compress.Local.RU("Single Compressed Sugar","Сжатый сахар");
Compress.Local.RU("Single Compressed Gunpowder","Сжатый порох");
Compress.Local.RU("Single Compressed Sugar Cane","Сжатый сахарный тростник");
Compress.Local.RU("Block of Nether Star","Блок из звезды Нижнего мира");
Compress.Local.RU("Single Compressed Clay","Сжатая глина");
Compress.Local.RU("Single Compressed Flint","Сжатый кремень");

//DOUBLE:
Compress.Local.RU("Double Compressed Cobblestone","Двукратно сжатый булыжник");
Compress.Local.RU("Double Compressed Stone","Двукратно сжатый камень");
Compress.Local.RU("Double Compressed Sand","Двукратно сжатый песок");
Compress.Local.RU("Double Compressed Dirt","Двукратно сжатая земля");
Compress.Local.RU("Double Compressed Gravel","Двукратно сжатый гравий");
Compress.Local.RU("Double Compressed Mossy Cobblestone","Двукратно сжатый замшелый булыжник");
Compress.Local.RU("Double Compressed End Stone","Двукратно сжатый камень Края");
Compress.Local.RU("Double Compressed Charcoal","Двукратно сжатый древесно-угольный блок");
Compress.Local.RU("Double Compressed Coal","Двукратно сжатый угольный блок");
Compress.Local.RU("Double Compressed Netherrack","Двукратно сжатый камень Нижнего мира");
Compress.Local.RU("Double Compressed Soul Sand","Двукратно сжатый песок душ");
Compress.Local.RU("Double Compressed Feathers","Двукратно сжатые перья");
Compress.Local.RU("Double Compressed Porkchop","Двукратно сжатая свинина");
Compress.Local.RU("Double Compressed Chicken","Двукратно сжатая курица");
Compress.Local.RU("Double Compressed Beef","Двукратно сжатая говядина");
Compress.Local.RU("Double Compressed Fish","Двукратно сжатая рыба");
Compress.Local.RU("Double Compressed Bones","Двукратно сжатые кости");
Compress.Local.RU("Double Compressed Eggs","Двукратно сжатые яйца");
Compress.Local.RU("Double Compressed Leather","Двукратно сжатая кожа");
Compress.Local.RU("Double Compressed Potatoes","Двукратно сжатый картофель");
Compress.Local.RU("Double Compressed Carrots","Двукратно сжатая морковь");
Compress.Local.RU("Double Compressed Nether Wart","Двукратно сжатый адский нарост");
Compress.Local.RU("Double Compressed Melon","Двукратно сжатый арбуз");
Compress.Local.RU("Double Compressed Apples","Двукратно сжатое яблоко");
Compress.Local.RU("Double Compressed Rotten Flesh","Двукратно сжатая гнилая плоть");
Compress.Local.RU("Double Compressed Blaze","Двукратно сжатый огненный стержень");
Compress.Local.RU("Double Compressed Spider Eyes","Двукратно сжатые паучьи глаза");
Compress.Local.RU("Double Compressed Ender Pearl","Двукратно сжатый жемчуг Края");
Compress.Local.RU("Double Compressed Sugar","Двукратно сжатый сахар");
Compress.Local.RU("Double Compressed Gunpowder","Двукратно сжатый порох");
Compress.Local.RU("Double Compressed Sugar Cane","Двукратно сжатый сахарный тростник");
Compress.Local.RU("Double Compressed Iron Block","Двукратно сжатый железный блок");
Compress.Local.RU("Double Compressed Gold Block","Двукратно сжатый золотой блок");
Compress.Local.RU("Double Compressed Diamond Block","Двукратно сжатый алмазный блок");
Compress.Local.RU("Double Compressed Emerald Block","Двукратно сжатый изумрудный блок");
Compress.Local.RU("Double Compressed Lazurite Block","Двукратно сжатый лазуритовый блок");
Compress.Local.RU("Double Compressed Redstone Block","Двукратно сжатый блок из красного камня");
Compress.Local.RU("Double Compressed Hay","Двукратно сжатый сноп сена");
Compress.Local.RU("Double Compressed Clay","Двукратно сжатая глина");
Compress.Local.RU("Double Compressed Flint","Двукратно сжатый кремень");
Compress.Local.RU("Double Compressed Slime","Двукратно сжатый блок слизи");

//TRIPLE:
Compress.Local.RU("Triple Compressed Cobblestone","Трёхкратно сжатый булыжник");
Compress.Local.RU("Triple Compressed Stone","Трёхкратно сжатый камень");
Compress.Local.RU("Triple Compressed Sand","Трёхкратно сжатый песок");
Compress.Local.RU("Triple Compressed Dirt","Трёхкратно сжатая земля");
Compress.Local.RU("Triple Compressed Gravel","Трёхкратно сжатый гравий");
Compress.Local.RU("Triple Compressed Mossy Cobblestone","Трёхкратно сжатый замшелый булыжник");
Compress.Local.RU("Triple Compressed End Stone","Трёхкратно сжатый камень Края");
Compress.Local.RU("Triple Compressed Charcoal","Трёхкратно сжатый древесно-угольный блок");
Compress.Local.RU("Triple Compressed Coal","Трёхкратно сжатый угольный блок");
Compress.Local.RU("Triple Compressed Netherrack","Трёхкратно сжатый камень Нижнего мира");
Compress.Local.RU("Triple Compressed Soul Sand","Трёхкратно сжатый песок душ");
Compress.Local.RU("Triple Compressed Feathers","Трёхкратно сжатые перья");
Compress.Local.RU("Triple Compressed Porkchop","Трёхкратно сжатая свинина");
Compress.Local.RU("Triple Compressed Chicken","Трёхкратно сжатая курица");
Compress.Local.RU("Triple Compressed Beef","Трёхкратно сжатая говядина");
Compress.Local.RU("Triple Compressed Fish","Трёхкратно сжатая рыба");
Compress.Local.RU("Triple Compressed Bones","Трёхкратно сжатые кости");
Compress.Local.RU("Triple Compressed Eggs","Трёхкратно сжатые яйца");
Compress.Local.RU("Triple Compressed Leather","Трёхкратно сжатая кожа");
Compress.Local.RU("Triple Compressed Potatoes","Трёхкратно сжатый картофель");
Compress.Local.RU("Triple Compressed Carrots","Трёхкратно сжатая морковь");
Compress.Local.RU("Triple Compressed Nether Wart","Трёхкратно сжатый адский нарост");
Compress.Local.RU("Triple Compressed Apples","Трёхкратно сжатое яблоко");
Compress.Local.RU("Triple Compressed Rotten Flesh","Трёхкратно сжатая гнилая плоть");
Compress.Local.RU("Triple Compressed Blaze","Трёхкратно сжатый огненный стержень");
Compress.Local.RU("Triple Compressed Spider Eyes","Трёхкратно сжатые паучьи глаза");
Compress.Local.RU("Triple Compressed Ender Pearl","Трёхкратно сжатый жемчуг Края");
Compress.Local.RU("Triple Compressed Sugar","Трёхкратно сжатый сахар");
Compress.Local.RU("Triple Compressed Gunpowder","Трёхкратно сжатый порох");
Compress.Local.RU("Triple Compressed Sugar Cane","Трёхкратно сжатый сахарный тростник");
Compress.Local.RU("Triple Compressed Iron Block","Трёхкратно сжатый железный блок");
Compress.Local.RU("Triple Compressed Gold Block","Трёхкратно сжатый золотой блок");
Compress.Local.RU("Triple Compressed Diamond Block","Трёхкратно сжатый алмазный блок");
Compress.Local.RU("Triple Compressed Emerald Block","Трёхкратно сжатый изумрудный блок");
Compress.Local.RU("Triple Compressed Lazurite Block","Трёхкратно сжатый лазуритовый блок");
Compress.Local.RU("Triple Compressed Redstone Block","Трёхкратно сжатый блок из красного камня");
Compress.Local.RU("Triple Compressed Hay","Трёхкратно сжатый сноп сена");
Compress.Local.RU("Triple Compressed Clay","Трёхкратно сжатая глина");
Compress.Local.RU("Triple Compressed Flint","Трёхкратно сжатый кремень");
Compress.Local.RU("Triple Compressed Slime","Трёхкратно сжатый блок слизи");

//QUADRUPLE:
Compress.Local.RU("Quadruple Compressed Cobblestone","Четырёхкратно сжатый булыжник");
Compress.Local.RU("Quadruple Compressed Stone","Четырёхкратно сжатый камень");
Compress.Local.RU("Quadruple Compressed Sand","Четырёхкратно сжатый песок");
Compress.Local.RU("Quadruple Compressed Dirt","Четырёхкратно сжатая земля");
Compress.Local.RU("Quadruple Compressed Gravel","Четырёхкратно сжатый гравий");
Compress.Local.RU("Quadruple Compressed Mossy Cobblestone","Четырёхкратно сжатый замшелый булыжник");
Compress.Local.RU("Quadruple Compressed End Stone","Четырёхкратно сжатый камень Края");
Compress.Local.RU("Quadruple Compressed Netherrack","Четырёхкратно сжатый камень Нижнего мира");
Compress.Local.RU("Quadruple Compressed Soul Sand","Четырёхкратно сжатый песок душ");
Compress.Local.RU("Quadruple Compressed Eggs","Четырёхкратно сжатые яйца");
Compress.Local.RU("Quadruple Compressed Rotten Flesh","Четырёхкратно сжатая гнилая плоть");
Compress.Local.RU("Quadruple Compressed Sugar Cane","Четырёхкратно сжатый сахарный тростник");
Compress.Local.RU("Quadruple Compressed Clay","Четырёхкратно сжатая глина");

//QUINTUPLE:
Compress.Local.RU("Quintuple Compressed Cobblestone","Пятикратно сжатый булыжник");
Compress.Local.RU("Quintuple Compressed Stone","Пятикратно сжатый камень");
Compress.Local.RU("Quintuple Compressed Sand","Пятикратно сжатый песок");
Compress.Local.RU("Quintuple Compressed Dirt","Пятикратно сжатая земля");
Compress.Local.RU("Quintuple Compressed Gravel","Пятикратно сжатый гравий");
Compress.Local.RU("Quintuple Compressed Mossy Cobblestone","Пятикратно сжатый замшелый булыжник");
Compress.Local.RU("Quintuple Compressed End Stone","Пятикратно сжатый камень Края");
Compress.Local.RU("Quintuple Compressed Netherrack","Пятикратно сжатый камень Нижнего мира");
Compress.Local.RU("Quintuple Compressed Soul Sand","Пятикратно сжатый песок душ");
Compress.Local.RU("Quintuple Compressed Eggs","Пятикратно сжатые яйца");
Compress.Local.RU("Quintuple Compressed Rotten Flesh","Пятикратно сжатая гнилая плоть");
Compress.Local.RU("Quintuple Compressed Sugar Cane","Пятикратно сжатый сахарный тростник");
Compress.Local.RU("Quintuple Compressed Clay","Пятикратно сжатая глина");

//SEXTUPLE:
Compress.Local.RU("Sextuple Compressed Cobblestone","Шестикратно сжатый булыжник");
Compress.Local.RU("Sextuple Compressed Stone","Шестикратно сжатый камень");
Compress.Local.RU("Sextuple Compressed Sand","Шестикратно сжатый песок");
Compress.Local.RU("Sextuple Compressed Dirt","Шестикратно сжатая земля");
Compress.Local.RU("Sextuple Compressed Gravel","Шестикратно сжатый гравий");
Compress.Local.RU("Sextuple Compressed Mossy Cobblestone","Шестикратно сжатый замшелый булыжник");
Compress.Local.RU("Sextuple Compressed End Stone","Шестикратно сжатый камень Края");
Compress.Local.RU("Sextuple Compressed Netherrack","Шестикратно сжатый камень Нижнего мира");
Compress.Local.RU("Sextuple Compressed Soul Sand","Шестикратно сжатый песок душ");
Compress.Local.RU("Sextuple Compressed Clay","Шестикратно сжатая глина");

//SEPTUPLE:
Compress.Local.RU("Septuple Compressed Cobblestone","Семикратно сжатый булыжник");
Compress.Local.RU("Septuple Compressed Stone","Семикратно сжатый камень");
Compress.Local.RU("Septuple Compressed Sand","Семикратно сжатый песок");
Compress.Local.RU("Septuple Compressed Dirt","Семикратно сжатая земля");
Compress.Local.RU("Septuple Compressed Gravel","Семикратно сжатый гравий");
Compress.Local.RU("Septuple Compressed Mossy Cobblestone","Семикратно сжатый замшелый булыжник");
Compress.Local.RU("Septuple Compressed End Stone","Семикратно сжатый камень Края");
Compress.Local.RU("Septuple Compressed Netherrack","Семикратно сжатый камень Нижнего мира");
Compress.Local.RU("Septuple Compressed Soul Sand","Семикратно сжатый песок душ");
Compress.Local.RU("Septuple Compressed Clay","Семикратно сжатая глина");

//OCTUPLE:
Compress.Local.RU("Octuple Compressed Cobblestone","Восьмикратно сжатый булыжник");
Compress.Local.RU("Octuple Compressed Stone","Восьмикратно сжатый камень");
Compress.Local.RU("Octuple Compressed Sand","Восьмикратно сжатый песок");
Compress.Local.RU("Octuple Compressed Dirt","Восьмикратно сжатая земля");
Compress.Local.RU("Octuple Compressed Gravel","Восьмикратно сжатый гравий");
Compress.Local.RU("Octuple Compressed Mossy Cobblestone","Восьмикратно сжатый замшелый булыжник");
Compress.Local.RU("Octuple Compressed End Stone","Восьмикратно сжатый камень Края");
Compress.Local.RU("Octuple Compressed Netherrack","Восьмикратно сжатый камень Нижнего мира");
Compress.Local.RU("Octuple Compressed Soul Sand","Восьмикратно сжатый песок душ");
Compress.Local.RU("Octuple Compressed Clay","Восьмикратно сжатая глина");

//NONUPLE:
Compress.Local.RU("Nonuple Compressed Cobblestone","Девятикратно сжатый булыжник");
Compress.Local.RU("Nonuple Compressed Stone","Девятикратно сжатый камень");
Compress.Local.RU("Nonuple Compressed Sand","Девятикратно сжатый песок");
Compress.Local.RU("Nonuple Compressed Dirt","Девятикратно сжатая земля");
Compress.Local.RU("Nonuple Compressed Gravel","Девятикратно сжатый гравий");
Compress.Local.RU("Nonuple Compressed Mossy Cobblestone","Девятикратно сжатый замшелый булыжник");
Compress.Local.RU("Nonuple Compressed End Stone","Девятикратно сжатый камень Края");
Compress.Local.RU("Nonuple Compressed Netherrack","Девятикратно сжатый камень Нижнего мира");
Compress.Local.RU("Nonuple Compressed Soul Sand","Девятикратно сжатый песок душ");
Compress.Local.RU("Nonuple Compressed Clay","Девятикратно сжатая глина");

//DECUPLE:
Compress.Local.RU("Decuple Compressed Cobblestone","Десятикратно сжатый булыжник");
Compress.Local.RU("Decuple Compressed Stone","Десятикратно сжатый камень");
Compress.Local.RU("Decuple Compressed Sand","Десятикратно сжатый песок");
Compress.Local.RU("Decuple Compressed Dirt","Десятикратно сжатая земля");
Compress.Local.RU("Decuple Compressed Gravel","Десятикратно сжатый гравий");
Compress.Local.RU("Decuple Compressed Mossy Cobblestone","Десятикратно сжатый замшелый булыжник");
Compress.Local.RU("Decuple Compressed End Stone","Десятикратно сжатый камень Края");
Compress.Local.RU("Decuple Compressed Netherrack","Десятикратно сжатый камень Нижнего мира");
Compress.Local.RU("Decuple Compressed Soul Sand","Десятикратно сжатый песок душ");
Compress.Local.RU("Decuple Compressed Clay","Десятикратно сжатая глина");