/*
//Machine;
mod_tip(BlockID.sagmill);
mod_tip(BlockID.alloySmelter);
//Conduit;
mod_tip(BlockID.fluidConduit);
mod_tip(BlockID.energyConduit);
mod_tip(BlockID.itemConduit);
//Generator;
mod_tip(BlockID.photovoltaicCell);
mod_tip(BlockID.advancedPhotovoltaicCell);
mod_tip(BlockID.vibrantPhotovoltaicCell);
mod_tip(BlockID.stirlingGen);
//Glass
mod_tip(BlockID.fusedGlass);
mod_tip(BlockID.fusedQuartz);
//Items
mod_tip(ItemID.basicGear);
mod_tip(ItemID.binderComposite);
mod_tip(ItemID.conduitBinder);
//Ingots
mod_tip(ItemID.itemYetaWrench);
mod_tip(ItemID.conductiveIron);
mod_tip(ItemID.silicon);
mod_tip(ItemID.vibrantAlloy);
mod_tip(ItemID.soulariumIngot);
mod_tip(ItemID.electricalSteel);
mod_tip(ItemID.darkSteel);
mod_tip(ItemID.energeticAlloy);
mod_tip(ItemID.vibrantNugget);
mod_tip(ItemID.vibrantCrystal);
mod_tip(ItemID.enderCrystal);
// Skulls
mod_tip(ItemID.endermanSkull);
mod_tip(ItemID.zombieSkull);
mod_tip(ItemID.skullZombieController);
mod_tip(ItemID.creeperSkull);
mod_tip(ItemID.skeletonSkull);
//Capacitor
mod_tip(ItemID.basicCapacitor);
mod_tip(ItemID.doublelayerCapacitor);
mod_tip(ItemID.octadicCapacitor);
*/
// END \__*__/

