let biomesNames = {
	//0: null,
	1: 'Plains',
	2: 'Desert',
	3: 'Extreme Hills',
	4: 'Forest',
	5: 'Taiga',
	6: 'Swampland',
	7: 'River',
	8: 'Nether Wastes',
	9: 'The End',
	10: 'Frozen Ocean',
	11: 'Frozen River',
	12: 'Snowy Tundra',
	13: 'Snowy Mountains',
	14: 'Mushroom Fields',
	15: 'Mushroom Field Shore', 
	16: 'Beach', 
	17: 'Desert Hills',
	18: 'Forest Hills',
	19: 'Taiga Hills',
	20: 'Extreme Hills Edge',
	21: 'Jungle',
	22: 'Jungle Hills',
	23: 'Jungle Edge',
	24: 'Deap Ocean',
	25: 'Stone Beach',
	26: 'Cold Beach',
	27: 'Birch Forest',
	28: 'Birch Forest Hills',
	29: 'Roofed Forest',
	30: 'Cold Taiga',
	31: 'Cold Taiga Hills',
	32: 'Mega Taiga',
	33: 'Mega Taiga Hills',
	34: 'Extreme Hills Plus Trees',
	35: 'Savanna',
	36: 'Savanna Plateau',
	37: 'Mesa',
	38: 'Mesa Plateau Stone',
	39: 'Mesa Plateau',

	42: 'Ocean',
	43: 'Legacy Frozen Ocean',
	44: 'Warm Ocean',
	45: 'Lucewarm Ocean',
	46: 'Cold Ocean',
	47: 'Deep Warm Ocean',
	48: 'Deep Lucewarm Ocean',
	49: 'Deep Cold Ocean',
	50: 'Deep Frozen Ocean',
	
	129: 'Sunflower Plains',
	130: 'Desert Mutated',
	131: 'Extreme Hills Mutated',
	132: 'Flower Forest',
	133: 'Taiga Mutated',
	134: 'Swampland Mutated',
		
	140: 'Ice Plains Spikes',
	
	149: 'Jungle Mutated',
	
	151: 'Jungle Edge Mutated',
	
	155: 'Birch Forest Mutated',
	156: 'Birch Forest Hills Mutated',
	157: 'Roofed Forest Mutated',
	158: 'Cold Taiga Mutated',
	
	160: 'Redwood Taiga Mutated',
	161: 'Redwood Taiga Hills Mutated',
	162: 'Extreme Hills plus Trees Mutated',
	163: 'Savanna Mutated',
	164: 'Savanna Plateau Mutated',
	165: 'Mesa Bruce',
	166: 'Mesa Plateau Stone Mutated',
	167: 'Mesa Plateau Mutated',
	168: 'Bamboo Jungle',
	169: 'Bamboo Jungle Hills',
	
	178: 'Sound Sand Valley',
	179: 'Crimson Forest',
	180: 'Warped Forest',
	181: 'Basalt Deltas',
	
	//new update
    182: 'Jagged Peaks',
    183: 'Frozen Peaks',
    184: 'Snowy Slopes',
    185: 'Grove',
    186: 'Meadow',
    187: 'Lush Caves',
    188: 'Dripstone Caves',
    189: 'Stony Peaks'

};
